version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

commands:
  install-deps:
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            pip install pytest flake8

jobs:
  test:
    executor: python-executor
    parallelism: 2
    steps:
      - install-deps
      - run:
          name: Ejecutar pruebas en paralelo
          command: |
            pytest test_cliente.py

  lint:
    executor: python-executor
    steps:
      - install-deps
      - run:
          name: Revisar estilo de código con flake8
          command: |
            flake8 . > flake8-report.txt || true
      - store_artifacts:
          path: flake8-report.txt
          destination: flake8-report

  run-script:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Crear input.txt simulado
          command: echo -e "1\n123\n4\n" > input.txt
      - run:
          name: Ejecutar main.py
          command: python main.py < input.txt

  security-scan:
    executor: python-executor
    steps:
      - install-deps
      - run:
          name: Escaneo de seguridad con bandit
          command: |
            pip install bandit
            bandit -r . > bandit-report.txt || true
      - store_artifacts:
          path: bandit-report.txt
          destination: bandit-report

workflows:
  version: 2

  build_and_test:
    jobs:
      - lint
      - test
      - security-scan
      - run-script:
          requires:
            - test

  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: main
    jobs:
      - lint
      - test
      - security-scan

notifications:
  webhooks:
    - url: https://hooks.slack.com/services/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
      events:
        - success
        - fail
        - fixed
        - on_hold
